[tls]
key = "./server-key.pem"
cert = "./server-cert.pem"
ca_cert = "./ca-cert.pem"

[network]
role = "server"
address = "10.10.0.1/24"

[[network.client]]
client_cert = "./server-cert.pem"
allowed_ips = "10.10.0.3/32"
